version: '3.1'

services:
  otusdb:
    image: mongo:4.2
    container_name: mongo
    restart: always #Перезапуск всегда
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./db/mongo:/data/db
